# Project information

site_name: Identity Round Robin
site_short_name: Identity Round Robin
site_description: 'A hands-on workshop to learn about a variety of AWS identity topics.'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://identity-round-robin.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/aws-identity-round-robin-workshop'
repo_url: 'https://github.com/aws-samples/aws-identity-round-robin-workshop'

# Copyright
copyright: '<a href="https://aws.amazon.com/privacy/" target="_blank">Privacy</a> | <a href="https://aws.amazon.com/terms/" target="_blank">Site terms</a> | &copy; 2020, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  features:
    - tabs

# Customization
extra_css:
  - 'stylesheets/custom.css'
  
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://awssecworkshops.com
    - icon: fontawesome/solid/shield-alt
      link: https://aws.amazon.com/security/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/awssecurityinfo?lang=en
    - icon: fontawesome/solid/rss-square
      link: https://aws.amazon.com/blogs/security/

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details


# Navigation
nav:
  - Overview: 'index.md'
  - 'Serverless Identity':
    - 'Scenario': 'serverless/index.md'
    - 'Task 1': 'serverless/task1.md'
    - 'Task 2': 'serverless/task2.md'
  - 'Access Delegation':
    - 'Scenario': 'delegation/index.md'
    - 'Build Phase': 'delegation/build.md'
    - 'Verify Phase': 'delegation/verify.md'
  - 'Permissions Boundaries - Advanced':
    - 'Scenario': 'permission-boundaries-advanced/index.md'
    - 'Build Phase': 'permission-boundaries-advanced/build.md'
    - 'Verify Phase': 'permission-boundaries-advanced/verify.md'

  - Contributing: 'contribute.md'
  - License: 'license.md'
